name: Deploy to Azure Function - lexureappfunc01   # ✅ ENGLISH KEYWORDS

on:
  push:
    branches:
      - main        # ← cámbialo a 'principal' si tu rama se llama así
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout code
      - name: Checkout source
        uses: actions/checkout@v3

      # 2) (Opcional) Configurar Python para Functions v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3) Empaquetar dependencias (solo si usas requirements.txt)
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt --target="./.python_packages/lib/site-packages"

      # 4) Desplegar con Publish Profile
      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: 'lexureappfunc01'                           # ← nombre exacto
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
          package: '.'                                          # carpeta raíz del código
