name: Deploy to Azure Function - lexureappfunc01

on:
  push:
    branches:
      - principal  # Asegúrate de que tu rama se llama así (cámbiala a 'main' si es necesario)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1
        with:
          app-name: lexureappfunc01  # Asegúrate que este es el nombre exacto de tu Azure Function App
          package: '.'
